### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by coalcarter** [tiagosiebler/binance#101]
I've installed the binance to use the binance WebSockets
I ran this command
npm i binance --save
but I got these warnings
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

and also when I run my script It says require is not defined 

Any solution to solve this issue?

**Comment by tiagosiebler** [comment]
There don't seem to be any issues in your install log. It's likely a configuration issue in how you've setup your node environment, although more general programming topics are outside the scope of this repo.

**Comment by tiagosiebler** [comment]
Side note, for more general guidance you could try asking on our [Node.js Algo Traders](https://t.me/nodetraders) engineering community on telegram.
