### ISSUE TITLE
Is this implementation compatible with Binance Futures?

### ISSUE THREAD

**Issue by watch-janick** [tiagosiebler/binance#121]
Is this implementation compatible with Binance Futures and does it work with the testnet?

Thanks!

**Comment by tiagosiebler** [comment]
Not yet but the next major release will be.

**Comment by watch-janick** [comment]
Any idea when the next major release will be... released? 😅

**Comment by tiagosiebler** [comment]
Not yet. Hope would be perhaps in a month or two but there's always a chance it can take longer. The new structure for the REST APIs is working well. I've got the majority of the spot/mining/margin endpoints integrated, though some categories are still missing. If you want to help flesh out the existing endpoints (as well as types and tests), [drop me a message](https://t.me/nodetraders). The new structure means it's simple to implement other binance API categories too, but next I'm working on sorting out the websocket implementation.

**Comment by watch-janick** [comment]
Alright, I will need to use the futures API very soon so I'll use another
library this time.

Good luck with the implementation! I really like the features of your
library unfortunately I'm short on time for this project otherwise I
would've gladly helped!

Thank you!

**Comment by tiagosiebler** [comment]
Hi @watch-janick - the next major release is up for beta testing if you're up to it, take a look at #122. Any help in expanded testing is hugely valuable. Drop any feedback in the PR (or open further issues) if needed. Thank you!
