### ISSUE TITLE
getKlines CORS issue

### ISSUE THREAD

**Issue by dylansproule** [tiagosiebler/binance#126]
Interesting, your example calls worked just fine with the updates however getKlines seems to be throwing me a server error dealing with CORS, when I revert back to the previous version no issues appear.

**Comment by tiagosiebler** [comment]
Interesting - I must be including a header that isn't needed (nor covered in their CORS configuration). Are you using the module directly or the webpack build?

In developer tools, can you right-click the request that's failing in the network tab and copy as fetch?
![Screenshot 2021-08-12 at 08 43 54](https://user-images.githubusercontent.com/14090872/129158011-3855e369-f31b-4f07-8907-e9431a682b50.png)

**Comment by tiagosiebler** [comment]
Closing this now. Feel free to reopen if you want to investigate this further. Thanks
