### ISSUE TITLE
Guidance on how to configure for testnet

### ISSUE THREAD

**Issue by d11wtq** [tiagosiebler/binance#151]
Thanks so much for this project. So far it's been working great!

So far I've been playing with the livenet performing read-only operations. I'm at a point now where I need to test some trade execution logic, which I'd obviously prefer to do on the testnet. I can't find any documentation on how to set this up using this package. It would be great if there was something in the README with an example connecting the MainClient and the WebsocketClient to testnet endpoints.

From the testnet dashboard.

![image](https://user-images.githubusercontent.com/37948/135698888-af316a3e-bb66-490d-8bcc-418cc3944ce1.png)

How do I specify which endpoint to call? ~How do I specify a private key for signing requests?~ Oh I see, you can generate an HMAC SHA256 key for testnet too.

**Comment by d11wtq** [comment]
All good, I figured it out. Pass `baseUrl` and `wsUrl` to the clients ❤️

**Comment by tiagosiebler** [comment]
> All good, I figured it out. Pass `baseUrl` and `wsUrl` to the clients ❤️

Glad to hear! If you have a chance to help improve the docs, that would be appreciated!
