### ISSUE TITLE
[COIN-M] coin margined futures support?

### ISSUE THREAD

**Issue by waterdrop01** [tiagosiebler/binance#152]
Hello,
Opening this issue to track the status of support for coin margined (**COIN-M**) futures on Binance in the API!
Thanks!

**Comment by tiagosiebler** [comment]
I've wanted to add it but not yet had the bandwidth. It should be relatively easy to clone the usdm client into a coinm client, then it's just updating any usdm references to coinm and checking all the API endpoints. I'll gladly review a pull request if you have the bandwidth to even start parts of it. Thanks!

**Comment by eugeneglova** [comment]
@tiagosiebler  please review https://github.com/tiagosiebler/binance/pull/305
