### ISSUE TITLE
Typo in method name

### ISSUE THREAD

**Issue by Sated** [tiagosiebler/binance#157]
![image](https://user-images.githubusercontent.com/66825082/141813426-0f6223c7-6e31-4f74-a80f-dbf7c740d6fa.png)
It looks like the method should be `/fapi/v1/countdownCancelAll`

**Comment by tiagosiebler** [comment]
Good catch! Looks like a mistake - I'd welcome a PR to fix it.

**Comment by tiagosiebler** [comment]
Will be fixed in the next release (v2.0.17, not published yet).
