### ISSUE TITLE
Unhandled exception during ws reconnect after network error

### ISSUE THREAD

**Issue by ShJavokhir** [tiagosiebler/binance#164]
Hi, when there is no internet connection, program just crashes. I think this should be handled. Thanks
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/46817680/142765318-8472c4a0-0c7c-467a-b73b-a6d88213e0dd.png">

**Comment by tiagosiebler** [comment]
Will be fixed in the next release (2.0.18), available shortly. Please let me know once you've had a chance to test.
