### ISSUE TITLE
DailyChangeStatistic type missing the "bidQty" and "askQty" properties

### ISSUE THREAD

**Issue by s-abbasi** [tiagosiebler/binance#165]
`binance.get24hrChangeStatististics()` returns type of `DailyChangeStatistic` and `DailyChangeStatistic[]` but what actually is returned is an array containing "bidQty" and "askQty"  props.

**Comment by tiagosiebler** [comment]
Is this with the `main-client` or `usdm-client`? 

Are you on the latest version? For the main client (used for spot markets), the URL is correctly mapped to this method:
https://github.com/tiagosiebler/binance/blob/master/src/main-client.ts#L262-L264

https://binance-docs.github.io/apidocs/spot/en/#24hr-ticker-price-change-statistics

And trying this URL in the browser also returns the correct data:
https://api.binance.com/api/v3/ticker/24hr

**Comment by s-abbasi** [comment]
Im using version 2.0.16 
main client

respond is correct. but the interface `DailyChangeStatistic` is missing these two props `bidQty: string` and `askQty: string`

see:
![Screen Shot 1400-09-08 at 14 00 33](https://user-images.githubusercontent.com/15096891/143852756-fad43573-e3dc-42c6-a413-ae805c421526.png)

this interface does not contain `bidQty: string` and `askQty: string`
https://github.com/tiagosiebler/binance/blob/4a41148efd97dfe5541509885a56d31b97469b05/src/types/spot.ts#L438

**Comment by tiagosiebler** [comment]
I see - I misunderstood your initial comment. Thanks for flagging this, will try to fix this with the next release.

**Comment by tiagosiebler** [comment]
Will be fixed in the next release (2.0.18), available shortly. Please let me know once you've had a chance to test.
