### ISSUE TITLE
can i query indicators of a market pair with websockets?

### ISSUE THREAD

**Issue by puneeth714** [tiagosiebler/binance#172]
How can I request the indicators values from the Binance web socket?

**Comment by tiagosiebler** [comment]
As far as I'm aware, unfortunately not possible. What you can do is either write your own code to do your indicator calculations for you, or you could use one of the many indicator libraries on npm. Some libraries you can try: `talib`, `tulind`, `ta.js`. There's quite a few on npm and github - just make sure to check them before adding them to a sensitive project.
