### ISSUE TITLE
Add support to testnet 😊

### ISSUE THREAD

**Issue by martudev** [tiagosiebler/binance#184]
Hello how are you? First of all beautiful the project very well documented and armed, congratulations! 

Second, I would like the project to have an option to connect to the testnet api, currently the binance testnet api does not support `/sapi/v1` only supports `/api/` therefore it is useless to change the option `baseUrl` with the binance testnet (https://testnet.binance.vision/).
To make the code simple, it occurred to me to add a parameter when making a `new MainClient()` that parameter would be `testnet: true` and it would look something like this:

```
const client = new MainClient({
    api_key: 'key',
    api_secret: 'key',
    testnet: true,
});
```

I would like to know what you think about it since it would be a big change to the code, if you want I can take care of carrying it out since it is something I need to do to test the bot that I am developing. Thank you very much and greetings! Martu

**Comment by tiagosiebler** [comment]
Thanks, glad you're enjoying the project! I like the idea to make testnet easier to use - your proposal sounds good to me. Maybe we can find a way to do this without a huge number of changes? 

Is it only the URL prefix that needs changing? 

Some thoughts:
- The **MainClient** (and other clients) have `RestClientOptions` in the constructor, this is where you're thinking to add an **optional** testnet boolean 👍 
- The **MainClient** extends the **BaseRestClient**, which has utility methods to make requests: https://github.com/tiagosiebler/binance/blob/master/src/util/BaseRestClient.ts#L113-L148
- All of these request methods end up calling **_call**(): https://github.com/tiagosiebler/binance/blob/master/src/util/BaseRestClient.ts#L153
- This could be a good place to check `if (this.options.testnet) {`, and if so, update the endpoint prefix. Pseudo code on how I imagine this could look:
```
function getTestnetEndpoint(endpoint: string): string {
 ... logic to replace prefix and return new value
}

public async _call(method: Method, endpoint: string, params?: any, isPrivate?: boolean, baseUrlOverride?: string): GenericAPIResponse {
  const resolvedEndpoint = this.options.testnet ? getTestnetEndpoint(endpoint) : endpoint;
```

Something like this would mean only a few changes to handle processing that endpoint update, and would mean anyone not interested in testnet isn't affected by this change (no performance impact either).

**Comment by martudev** [comment]
Hi @tiagosiebler how are you?, First of all, thank you very much for your comment and commitment
Recently I was investigating more in depth what I had told you and I ran into some problems since apparently binance does not support `/sapi/` in the testnet therefore it would not be possible to obtain the same information from the testnet. The only way i see if we want to use testnet is not use the functions that calls `/sapi/`. 
Also according to what I was talking about, there are many problems with the binance testnet since there are not many servers pending transactions, therefore sometimes it tends to crash and throw errors. Capable is better to invest money and test on the mainnet. Thanks for youre time and for all!

**Comment by tiagosiebler** [comment]
> Hi @tiagosiebler how are you?, First of all, thank you very much for your comment and commitment Recently I was investigating more in depth what I had told you and I ran into some problems since apparently binance does not support `/sapi/` in the testnet therefore it would not be possible to obtain the same information from the testnet. The only way i see if we want to use testnet is not use the functions that calls `/sapi/`. Also according to what I was talking about, there are many problems with the binance testnet since there are not many servers pending transactions, therefore sometimes it tends to crash and throw errors. Capable is better to invest money and test on the mainnet. Thanks for youre time and for all!

Yes, I normally do my testing on mainnet too. Sometimes testnet (for all of these exchanges) doesn't behave the same as mainnet, so even just for testing the api it's not a reliable way to compare. I'll close this discussion for now, but if you want to resume it feel free.
