### ISSUE TITLE
getExchangeInfo returns an error when providing a symbols param

### ISSUE THREAD

**Issue by SebHex** [tiagosiebler/binance#200]
Using [getExchangeInfo](https://github.com/tiagosiebler/binance/blob/7b3c66a0e0702c1ed5c8b76bc45b2ee2a1d89eaa/src/main-client.ts#L239) with `symbol`/`symbols` params, returns an error:

```JSON
{
  "code": -1104,
  "msg": "Not all sent parameters were read; read '0' parameter(s) but was sent '1'."
}
```

## Example

Using:
```TypeScript
const exchangeInfo = await client.getExchangeInfo({
  symbol: 'BTCUSDT'
})
```
❌ Submits the URL:
https://api.binance.com/api/v3/exchangeInfo?BTCUSDT

✔ The URL should be:
https://api.binance.com/api/v3/exchangeInfo?symbol=BTCUSDT

## Temporary solution

A temp solution for using the `symbol` param:
```TypeScript
const exchangeInfo = await client.getExchangeInfo({
  symbol: 'symbol=BTCUSDT'
})
```

## Binance docs

[Exchange info](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#exchange-information)

**Comment by tiagosiebler** [comment]
Thanks for pointing out the solution as well, will be fixed shortly in the next release.

**Comment by giveerr** [comment]
I think the same should apply to symbols.

Get the same error when I try to run this code:

```js
client.getExchangeInfo({
    symbols: ['BTCUSDT' , 'BNBUSDT']
})
```
