### ISSUE TITLE
Typo in declarations

### ISSUE THREAD

**Issue by flashup** [tiagosiebler/binance#203]
Hello, here should be `cummulativeQuoteQty` with double mm instead of `cumulativeQuoteQty` in a few places:
https://github.com/tiagosiebler/binance/blob/master/src/types/spot.ts

Original API:
https://binance-docs.github.io/apidocs/spot/en/#new-order-trade

**Comment by A-ndy-git** [comment]
This has been resolved in `v2.0.28` via #206.
