### ISSUE TITLE
Failed to keep WS alive for listen key after 3 attempts

### ISSUE THREAD

**Issue by raymondjhs** [tiagosiebler/binance#205]
When run the websockets, it usally get this error every one or two days.
It seems a problem to keet listenKey alive.

[
  'User key refresh failed due to error, trying again with short delay',
  {
    category: 'binance-ws',
    listenKey: 'm6EMQyy35lILqXQX14BSHIwwYGIWnBehI2YD2S2mchsCCvXFobrZ6HpkA5jVwM0S',
    error: Error: Client network socket disconnected before secure TLS connection was established
        at connResetException (internal/errors.js:607:14)
        at TLSSocket.onConnectEnd (_tls_wrap.js:1554:19)
        at TLSSocket.emit (events.js:388:22)
        at endReadableNT (internal/streams/readable.js:1336:12)
        at processTicksAndRejections (internal/process/task_queues.js:82:21) {
      code: 'ECONNRESET',
      path: null,
      host: 'fapi.binance.com',
      port: 443,
      localAddress: undefined,
      config: [Object],
      request: [Writable],
      response: undefined,
      isAxiosError: true,
      toJSON: [Function: toJSON]
    },
    keepAliveAttempts: 2
  } 
] 
WebSocket Error: FATAL: Failed to keep WS alive for listen key after 3 attempts
WebSocket Error: Failed to connect to USD Futures user data
WebSocket Error: Exception trying to spawn user data stream

**Comment by tiagosiebler** [comment]
Thanks for opening a ticket. It's not a fatal issue as there's a fallback workflow when this happens. Looks like in this instance your environment lost connectivity to binance (either your network or binance was having issues).

Eventually the connector gave up trying to send the keep-alive request for your listen key and resorted to creating a new listen key (and therefore respawning a fresh user-data stream) for you. This is automatic & under-the-hood, thus doesn't require any attention unless you can improve connectivity in the environment that saw this. You can see the logic here:
https://github.com/tiagosiebler/binance/blob/master/src/websocket-client.ts#L769-L787

Keep alive is sent at intervals, if it fails 3 times in a row it assumes something went really wrong and just does a full-reset of your user data stream.

**Comment by raymondjhs** [comment]
Thank you for response.
When this problem came out, I tried to close the script and restart it, every time it recovered normal. So I doubt whether it's the   problem of network connectivity?

**Comment by tiagosiebler** [comment]
The reason I suspect a connectivity scenario is because of the exception: `ECONNRESET`. If you're connecting to a server and you're getting connection-reset style errors, it's either your network or the server can't handle the connection (e.g. overload on the server).
