### ISSUE TITLE
Add staking endpoints

### ISSUE THREAD

**Issue by tiagosiebler** [tiagosiebler/binance#213]
https://binance-docs.github.io/apidocs/spot/en/#staking-endpoints

**Comment by lobobruno** [comment]
PR  #234  with some implementation!! 3 endpoints todo: 

https://binance-docs.github.io/apidocs/spot/en/#purchase-staking-product-user_data
https://binance-docs.github.io/apidocs/spot/en/#redeem-staking-product-user_data
https://binance-docs.github.io/apidocs/spot/en/#set-auto-staking-user_data
