### ISSUE TITLE
Consistency in naming?

### ISSUE THREAD

**Issue by BrandonCopley** [tiagosiebler/binance#22]
bestBidPrice is called bestBid.

This is inconsistent with bestAskPrice defining the bestAskPrice in beautify.

**Comment by aarongarvey** [comment]
You are correct.  I would fix it right now, but I don't want to break anyone's code.  

That said, I've got a number of improvements coming for the websocket portion of the API, which hasn't gotten as much love as the REST side of things yet.  More specifically, offXXX calls to close sockets, some reconnect functionality, and tests.  If you think of any additional functionality you'd like to see please let me know.

Once all that's in I'll revisit the beautification and bump the version to 2.0.

**Comment by BrandonCopley** [comment]
Awesome, Love the repo! Just commenting as I start integrating! thanks.

-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060 <(512)%20784-6060>

e: copley.brandon@gmail.com

**Comment by BrandonCopley** [comment]
I really want something "onAllTrades" this may just have to be a helper function though. just like onAllTickers

**Comment by aarongarvey** [comment]
The all market tickers stream is actually provided by binance(https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#all-market-tickers-stream).    You're wanting every individual trade for every symbol on the exchange?

**Comment by BrandonCopley** [comment]
Yes, every trade every symbol.

The data I'm trying to get is the "last trade price" which for some reason
doesn't appear to be included in the all market tickers data.

-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060 <(512)%20784-6060>

e: copley.brandon@gmail.com

**Comment by tiagosiebler** [comment]
Closing this old ticket. A later refactor should introduce better naming consistency.
