### ISSUE TITLE
Reaching blocking and fetchTimeOffset

### ISSUE THREAD

**Issue by skliarovartem** [tiagosiebler/binance#231]
I found that MainClient is trying to make `fetchTimeOffset` request automatically all the time even if my IP is blocked and in this way it keeps account blocked. Is it possible to control this request and don't do it automatically?

**Comment by tiagosiebler** [comment]
It's the time sync feature, which I've started turning off by default (bybit, soon ftx & binance too). You can turn it off using the first param of the construtor:
https://github.com/tiagosiebler/binance/blob/master/src/main-client.ts#L140

Set `disableTimeSync` to `true`. You can also manipulate the timing, if you want to keep it on, but I'm increasingly convinced it causes more recv window problems than it solves. I've also disabled it in my own usage of my connector for some time now and it's been perfectly stable.

**Comment by skliarovartem** [comment]
I found this crucial, because I mange different account in my app, and for each time when I need to make request I was creating new instance of client, and it was not destroyed because of this interval, so my IP was blocked often. Now it works fine without `disableTimeSync`

**Comment by tiagosiebler** [comment]
> I found this crucial, because I mange different account in my app, and for each time when I need to make request I was creating new instance of client, and it was not destroyed because of this interval, so my IP was blocked often. Now it works fine without `disableTimeSync`

Glad to hear that resolved it! Thanks for letting me know. I'll turn it off by default soon, maybe in the next release. Hope you're otherwise enjoying my connectors.
