### ISSUE TITLE
Support for COIN-M user data stream

### ISSUE THREAD

**Issue by skliarovartem** [tiagosiebler/binance#242]
Trying to connect to futures websockets:
```
const ws = new WebsocketClient({
                        api_key: wallet.apiKey,
                        api_secret: wallet.apiSecret,
                        beautify: true,
                        baseUrl: 'https://fapi.binance.com',
                        wsUrl: 'wss://fstream.binance.com',
                    });
```
And getting error:
`{ wsKey: 'spot_userData', error: "Unexpected '<'" }`

**Comment by tiagosiebler** [comment]
You shouldn't need to override the urls. The WS client handles this for you. Here's an example for USD Futures:
https://github.com/tiagosiebler/awesome-crypto-examples/blob/master/src/exchanges/binance/account-events/futures-balance-update.ts#L20-L68

**Comment by tiagosiebler** [comment]
Another example here:
https://github.com/tiagosiebler/binance/blob/master/examples/ws-userdata.ts#L116

**Comment by skliarovartem** [comment]
Awesome!

**Comment by skliarovartem** [comment]
As I understand `subscribeUsdFuturesUserDataStream` works for USDT-M. Is it possible also to subscribe to COIN-M? 
Many thanks!

**Comment by tiagosiebler** [comment]
Hmm unfortunately I haven't implemented COIN-M yet...
https://github.com/tiagosiebler/binance/blob/master/src/websocket-client.ts#L1845-L1869

It should be relatively straight forward by adapting what subscribeUsdFuturesUserDataStream() does into what the docs say for COIN-M

**Comment by skliarovartem** [comment]
Ok, I have created a fork and implemented there `subscribeCoinFuturesUserDataStream` of course rest client is empty right now, I use direct requests...

**Comment by tiagosiebler** [comment]
> Ok, I have created a fork and implemented there `subscribeCoinFuturesUserDataStream` of course rest client is empty right now, I use direct requests...

Cool, will you be making a pull request or would you prefer me to do it? Yes, the rest client for coinm is still a bit empty, it was only recently started by another user, but we can start adding methods to it for any needed endpoints.

**Comment by skliarovartem** [comment]
ok, I will make pr, but next week

**Comment by tiagosiebler** [comment]
Supported since a few releases ago
