### ISSUE TITLE
Support for getting margin balance

### ISSUE THREAD

**Issue by guyappy** [tiagosiebler/binance#257]
Hi,

I was looking what function to call in order to get the following data;
![image](https://user-images.githubusercontent.com/15813315/202504719-930b134b-d6ce-4109-b8e5-9e72582de386.png)

from the binance UI, it makes the following call:
'https://www.binance.com/bapi/asset/v2/private/asset-service/wallet/balance?needBalanceDetail=true'

Is this API supported through this project or is there a workaround so that I can easily make this call?

thank you so much in advance

**Comment by tiagosiebler** [comment]
The site might have it's own api. Best place to check is the official api docs to see if there's an endpoint with the data you're looking for. This one looks interesting:
https://binance-docs.github.io/apidocs/spot/en/#query-cross-margin-account-details-user_data

In my connector, `margin` endpoints are part of the main client. There's already a method here for this endpoint you can try:
https://github.com/tiagosiebler/binance/blob/master/src/main-client.ts#L841

One example for using the main client to make rest api calls: https://github.com/tiagosiebler/binance/blob/master/examples/rest-spot-private-misc.ts
