### ISSUE TITLE
add 1s kline interval

### ISSUE THREAD

**Issue by betavr** [tiagosiebler/binance#258]
Binance added support for 1s kline interval:

https://www.binance.com/en/blog/markets/new-1second-interval-feature-now-available-on-spot-and-margin-charts-9151369240338163004
https://testnet.binance.vision (scroll down to 2022-09-07 changes)

Proposed change:

```typescript
export declare type KlineInterval = '1s' | '1m' | '3m' | '5m' | '15m' | '30m' | '1h' | '2h' | '4h' | '6h' | '8h' | '12h' | '1d' | '3d' | '1w' | '1M';
```

**Comment by tiagosiebler** [comment]
Will be included in #261. Thanks!
