### ISSUE TITLE
Timestamp ahead & handling position updates in binance futures

### ISSUE THREAD

**Issue by ash-hashtag** [tiagosiebler/binance#260]
```
  code: -1021,
  message: "Timestamp for this request was 1000ms ahead of the server's time.",
  body: {
    code: -1021,
    msg: "Timestamp for this request was 1000ms ahead of the server's time."
  },
```

when using USDMClient.getPositions

doesn't happen always tho,

and another issue, even when I send symbols like in the getPositions([ { symbol: 'BTCUSDT' } ]), it fetches every other positions even positions I never had, so with 0s. and Can I subscribe to listen to my futures positions changes, with WebsocketClient, like every 2-5 seconds?

**Comment by tiagosiebler** [comment]
For the timestamp error, does it work fine when you first restart the process (but start happening later after running for a while)? 

I would recommend using `disableTimeSync: true` in the rest client options:
```javascript
const client = new USDMClient({
  api_key: key,
  api_secret: secret,
  disableTimeSync: true
});
```

My connectors have a time sync feature. They will regularly query the time endpoint to estimate network latency and/or differences between server time and client time. However, I think the current way it works is too simple, so it takes one slow reply for the client to over-estimate that gap between server and client time. The result is what you saw. It's not the only reason this can happen, but I do think it does often cause this to happen too. 

I've been testing for a while now with time sync disabled, across my connectors, and it seems more stable this way.

I've disabled this feature by default in my other connectors and will disable it by default in this connector in the next release. In the meantime, turning the feature off should reduce the chances of you seeing this kind of timestamp error (assuming your machine time is in sync over something like `ntp`).

**Comment by tiagosiebler** [comment]
Regarding the positions question, your parameters are slightly off. You're passing an array into `getPositions`. 

This method only accepts an object. Either pass one symbol, to check only one position:
```javascript
const onePosition = await getPositions({ symbol: 'BTCUSDT' });
```

Or pass no params to get all positions:
```javascript
const allPositions = await getPositions();
```

What I do in my own systems:
- Subscribe to the user data stream for futures (`subscribeUsdFuturesUserDataStream()` on the ws client)
- Query getPositions() for all positions and store the result (e.g. in an object keyed by symbol & position side)
- Update this store when any ws position updates come in.

Lastly, if the ws client emits a `reconnected` event, fetch and update positions again via REST to ensure I'm in sync:
```javascript
  binanceWs.on('reconnected', async (event) => {
    if (
      typeof event?.wsKey === 'string' &&
      event.wsKey.toLowerCase().includes('userdata')
    ) {
      Logger.info(`Ws reconnected, checking balance, positions & orders...`);
      await updateWalletBalance(exchangeApi, state, true);
      await syncPositionsAndCheckOrders();
      const e = new Error(`WS reconnected (userData) - executed full sync`);
      captureException(e);
    } else {
      Logger.info(`Ws ${event?.wsKey} reconnected`);
      const e = new Error(`WS reconnected (${event?.wsKey})`);
      captureException(e);
    }
  });
```

This way I can completely rely on position updates coming over the websocket instead of having to regularly poll the rest api (unless I see a chance of being out of sync, where I do ask the REST API for the current state).

**Comment by tiagosiebler** [comment]
Ah lastly, subscribing and handling user data (position) updates in usdm futures (with typescript):
```typescript
  binanceWs.subscribeUsdFuturesUserDataStream();
  binanceWs.on(
    'formattedUserDataMessage',
    (data: WsMessageFuturesUserDataEventFormatted) =>
      onBinanceFuturesUserDataEvent(data),
  );

async function onBinanceFuturesUserDataEvent(
  event: WsMessageFuturesUserDataEventFormatted,
): Promise<void> {
  const dt = new Date();
  trackInternalEventDt('wsFuturesUserData', dt);

  switch (event.eventType) {
    case 'ORDER_TRADE_UPDATE': {
      onOrderUpdateEvent(event, dt);
      break;
    }
    case 'ACCOUNT_UPDATE': {
      onAccountUpdateEvent(event, dt);
      break;
    }
    default: {
      Logger.warn(
        `onFuturesUserDataEvent(${
          event.eventType
        }): unhandled event type: ${JSON.stringify(event, null, 2)}`,
      );
    }
  }
}
```

The `ACCOUNT_UPDATE` case exposes `event.updateData.updatedPositions`, which has similar data to the getPositions api call. I'd recommend trying it out a bit with breakpoints or logs too see what it looks like.

There's info here on some of the values available in these events, although the above example looks at the beautified version (so the property names are readable thanks to the ws client and floats are parsed from string to number)
https://binance-docs.github.io/apidocs/futures/en/#event-balance-and-position-update

**Comment by ash-hashtag** [comment]
I don't know why but I can't get any updates with WebsocketClient except for ping pongs, I checked it with copying it from readme with default logger, no errors

**Comment by tiagosiebler** [comment]
> I don't know why but I can't get any updates with WebsocketClient except for ping pongs, I checked it with copying it from readme with default logger, no errors

The `formattedMessage` event only happens if you have `beautify: true` in the ws client options - check the example:
https://github.com/tiagosiebler/binance/blob/master/examples/ws-userdata.ts#L22-L27

Raw messages are always emitted via the `message` event. Could it be you didn't use `beautify: true`? Check out the above example for a full workflow on consuming user data events with the beautifier.

**Comment by tiagosiebler** [comment]
Let me know whether or not you get the ws client working. Will keep this open for a bit until then.

**Comment by ash-hashtag** [comment]
I have set beautify: true

**Comment by tiagosiebler** [comment]
Just to double check everything then, did you call the "subscribe" methods, like the example does?
https://github.com/tiagosiebler/binance/blob/master/examples/ws-userdata.ts#L117-L120

Are you triggering an action in your account when you expect to see an event? It's important to note that these websockets only emit events when something happens (e.g. you place/cancel an order, an order is filled, you transfer funds from spot to futures, etc). One example of a valid test is:
- Prepare the ws client with beautifier true
- Call `subscribeUsdFuturesUserDataStream()` to open the futures user data stream.
- On the binance website, set a limit order in binance futures (or open a position if you want).

This should trigger both a `message` event with the raw data and a `formattedMessage` event with the beautified version of the event.

**Comment by ash-hashtag** [comment]
> Are you triggering an action in your account when you expect to see an event? It's important to note that these websockets only emit events when something happens (e.g. you place/cancel an order, an order is filled, you transfer funds from spot to futures, etc)

Ah that makes sense, Sorry I thought I would get my future positions, every 3 seconds, no I'm not triggering anything, what do you

**Comment by tiagosiebler** [comment]
Ah yes, that's a common misunderstanding. These are essentially only change events. You will only receive an event when something changed in your account. If you just want to query the current state (regardless of change), you'll need to use the REST API.
