### ISSUE TITLE
Setup the websocket to handle reconnects

### ISSUE THREAD

**Issue by zoeyg** [tiagosiebler/binance#29]
Need to figure out how to do this, which indications are given by ws that there's been a connection error.  A number of the routes push data every second.  Should be possible to attempt a reconnect if nothing is received for X amount of seconds.  Maybe have incremental back off on the reconnects.  More info/inspiration here: https://github.com/issc29/binance/commit/76bfeaf9a038e3d87a64062af26736677de5ef82

**Comment by dreyescat** [comment]
You can find additional information at:
- [Websocket client implementation for auto reconnect](https://github.com/websockets/ws/wiki/Websocket-client-implementation-for-auto-reconnect)
- [reconnecting-websocket](https://github.com/pladaria/reconnecting-websocket)

The first one is a simple wrapper while the latter is a *full fledged* library. Hope it helps.

**Comment by talvasconcelos** [comment]
Is this implemented yet? @aarongarvey @issc29

**Comment by laurynas-karvelis** [comment]
Could [this error handler](https://github.com/aarongarvey/binance/blob/48e0f55974f07655d671a2cec1959a8106851894/lib/ws.js#L51) be utilised to attempt WS reconnection should the error occur. Additionally, `.on('close', cb)` handler should be implemented with a reconnection strategy.

**Comment by talvasconcelos** [comment]
Take a look at this : https://github.com/lukeed/sockette

**Comment by tiagosiebler** [comment]
Fixed in #122
