### ISSUE TITLE
Create examples for how to use each library method

### ISSUE THREAD

**Issue by talvasconcelos** [tiagosiebler/binance#30]
I'm trying to get the quantity and price to place an order but I'm failing miserably. Math is really not my thing...
I have the exchange Info with the filters for each pair... whatt i want to achieve in this particular order (although I'd like a universal solution) is to get balance from btc, place order with that amount. then get balance of bought asset and sell that amount.

the problem is I'm failing to get the right amount to place the order, need to round it based on the min quantity and min notonial.

can someone please share some solution/suggestion for this?

**Comment by aarongarvey** [comment]
This is not the place to be asking this kind of question.  These issues are for problems with the library or potential enhancements to it, not a support line for javascript or the binance API.

However, without someone knowing more specifics about your question it's going to be hard to answer it as is.  What's the specific error you're getting, and what's your current code look like?  What have you tried that's not working and how have you tried to troubleshoot it?  You should try looking through the [official docs](https://github.com/binance-exchange/binance-official-api-docs) for answers, or maybe try searching through or asking a question on stackoverflow.  Maybe this is what you're looking for https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round?

**Comment by aarongarvey** [comment]
I've decided I'm going to repurpose your issue and use it to track an enhancement to the library.  That is, adding examples for each library method.

**Comment by talvasconcelos** [comment]
Thanks, sorry for the question. Anyway i managed to solve it by copying zenbot's solution.

```
function roundToNearest(numToRound) {
    let numToRoundTo = minQty // value from the exchange filters
    numToRoundTo = 1 / (numToRoundTo)
    return Math.floor(numToRound * numToRoundTo) / numToRoundTo
  }
```

**Comment by aarongarvey** [comment]
@talvasconcelos Would you mind sharing the rest of your code?  Perhaps I could use it as an example for others

**Comment by talvasconcelos** [comment]
@aarongarvey i can give some help with that if you need. I'm building (or at least trying) a scanner for Binance.

**Comment by aarongarvey** [comment]
Works for me, and thanks!

**Comment by talvasconcelos** [comment]
@aarongarvey here's a small gist with some examples... it's a bit messy, if you have any troubles please contact me. But i guess you can easilly adapt from there.

https://gist.github.com/talvasconcelos/4fdb25f51ea34ad457ddcbb60156b330

**Comment by talvasconcelos** [comment]
Had to add this for MIN_NOTONIAL filter for orders to go through:

```
function getOrderMinSize(currency) {
    if (currency === 'BTC') return 0.002
    else if (currency === 'ETH') return 0.02
    else return 1
  }
```

Hope this can help you @aarongarvey if you need i can make some dummy examples!

**Comment by aarongarvey** [comment]
Thanks for the code.  I think I've decided on what is probably the best way to approach this, and that's an examples directory with individual files that each show a common task or route, and even better if the file is executable on it's own.  If you've got the time and wanna create some, by all means, go for it.

**Comment by apexearth** [comment]
Somewhat on topic -- I've written a function in my own project that processes the lot size, min notional, and step size filters and returns a modified quantity and price which should fit within the filter requirements. I'm thinking of porting it into my fork of this binance repository. Since everyone who does some math on quantities and prices is going to have to do this work, I think it would be appropriate to have something inside of this package.

**Comment by apexearth** [comment]
Example: https://github.com/apexearth/binance/commit/59d7fe543b244315a17c84b1ee9caf6d26d14f5e

**Comment by aarongarvey** [comment]
@apexearth Took a quick look at the code and it looks great.  I think having an example in the readme would be good as well.  Then if you wanna create a pull request, go for it and I'll merge it back into master.
