### ISSUE TITLE
Because of ping/pong - Binance drops connection with error 1006

### ISSUE THREAD

**Issue by mr-smit** [tiagosiebler/binance#304]
How to replicate:

Connect to 20 symbols and fetch:
subscribeSymbolBookTicker spot+usdm
subscribeKlines 1m spot+usdm

by default ping pong is: 
      pongTimeout: 7500,
      pingInterval: 10000,

But binance has a LIMIT 
```
WebSocket connections have a limit of 10 incoming messages per second. A message is considered:
A PING frame
A PONG frame
A JSON control message (e.g. subscribe, unsubscribe)
```
because "binance npm" are creating separate socket to server, we will have over 20*4=80 connections, and every connection will send a ping/pong frame, so we will send 80 ping pong and the limit is reached and binance is dropping our connections, this will triger massive reconnections

right now I thinking how to bypass this limitation.. something like creating a loop with different timeout parameters, multi thread or something custom.. thinking..

**Comment by tiagosiebler** [comment]
This incoming message per second is per connection. 
> A connection that goes beyond the limit will be disconnected

Since each topic is a separate connection, with the default ping/pong you should never be able to reach this limit (one ping frame every 7.5 seconds)
