### ISSUE TITLE
Missing UniversalTransfer types

### ISSUE THREAD

**Issue by emiliocr90** [tiagosiebler/binance#316]
at types/spot.ts, several types are missing.
additionally, several params are missing at UniversalTransferParams interface.

https://binance-docs.github.io/apidocs/spot/en/#user-universal-transfer-user_data

**Comment by tiagosiebler** [comment]
Hi, yes - it's been an incremental process to add these types as well as some of the currently missing endpoints. Contributions via pull requests are very welcome, no matter how small.

**Comment by emiliocr90** [comment]
> Hi, yes - it's been an incremental process to add these types as well as some of the currently missing endpoints. Contributions via pull requests are very welcome, no matter how small.

I will send pull requests whenever I find issues. No problem!

**Comment by emiliocr90** [comment]
this has been resolved with PR #317
