### ISSUE TITLE
small mistake in the spelling of get24hrChangeStatististics

### ISSUE THREAD

**Issue by anymos** [tiagosiebler/binance#321]
really not a pb but, just see it so I report get24hrChangeStatististics shall be get24hrChangeStatistics

**Comment by tiagosiebler** [comment]
Hi, thanks for reporting this. It's deprecated since v2.4.0 (#306), in favour of the corrected function name `get24hrChangeStatistics` in both the USDM and COINM futures clients. If you notice any other mistakes, please let me know. Thanks!
