### ISSUE TITLE
Websocket dependency conflict

### ISSUE THREAD

**Issue by alexk984** [tiagosiebler/binance#322]
After install this package I have this error when creating websocket:

    TypeError: ws_1.WebSocketServer is not a constructor

In this code:

     import { WebSocketServer } from 'ws'

     const ws = new WebSocketServer({ port: 9001 })

I see this difference in yarn.lock file:
<img width="646" alt="image" src="https://user-images.githubusercontent.com/893697/232131595-7efd540c-10e5-4091-a24b-b5624fd28554.png">

<img width="223" alt="image" src="https://user-images.githubusercontent.com/893697/232131210-741f8d3e-8527-4933-9df3-081f03616428.png">

How can I fix it?

**Comment by tiagosiebler** [comment]
Is this because the version of `ws` used in this package is older than yours? Can you give me a tiny example to reproduce the issue? Thanks
