### ISSUE TITLE
Does it have endpoints for mining?

### ISSUE THREAD

**Issue by nandokferrari** [tiagosiebler/binance#357]
Hello there, first of all, thank you for this package.

Did you implement methods for consuming the **mining endpoints**?
https://binance-docs.github.io/apidocs/spot/en/#mining-endpoints

I am looking for in your docs, but could not find anything related.

Thanks!

**Comment by tiagosiebler** [comment]
Hello! Doesn't seem like anyone has added them yet - they would be in the MainClient (which has all the endpoints in the "spot" category of the api docs), somewhere around here:
https://github.com/tiagosiebler/binance/blob/master/src/main-client.ts#L1124

Should be simple to add though if you follow the pattern of other similar endpoints. If it's a private get/post request, use getPrivate/postPrivate. If it's public, use get/post(), similar to the other methods in this file. 

I'd very much welcome a pull request to add the ones that you need (or all the ones that are in this category, if you're feeling generous).

**Comment by JJ-Cro** [comment]
Hey, these endpoints are added now. If you still need them. This SDK has full REST coverage now.
