### ISSUE TITLE
Missing time in force

### ISSUE THREAD

**Issue by tiagosiebler** [tiagosiebler/binance#358]
https://github.com/tiagosiebler/binance/blob/master/src/types/shared.ts#L26

add `GTX`

![telegram-cloud-photo-size-4-5958769616119512185-x](https://github.com/tiagosiebler/binance/assets/14090872/e2a12bd2-fa85-434b-943a-b3bbfcc5abae)

**Comment by shaharyakir** [comment]
duplicate with #329 

also GTD is missing

**Comment by tiagosiebler** [comment]
Thanks, will include these with #380.

**Comment by tiagosiebler** [comment]
Fixed in v2.9.0 via #380
