### ISSUE TITLE
Add missing simple-earn endpoints

### ISSUE THREAD

**Issue by OrpineJelly** [tiagosiebler/binance#386]
Is there any plan to implement the simple-earn api?

**Comment by tiagosiebler** [comment]
Not yet, I typically prioritise the ones I personally need or those that my [sponsors](https://github.com/sponsors/tiagosiebler) regularly ask for. Pull requests are also welcome to help improve the sdk.

**Comment by JJ-Cro** [comment]
All endpoints have been added, SDK provides full REST coverage now!

**Comment by OrpineJelly** [comment]
> All endpoints have been added, SDK provides full REST coverage now!

thanks!
