### ISSUE TITLE
Missing API endpoint for Query Commission Rates (USER_DATA)

### ISSUE THREAD

**Issue by dutu** [tiagosiebler/binance#391]
Endpoint for [Query Commission Rates (USER_DATA) ](https://binance-docs.github.io/apidocs/spot/en/#query-commission-rates-user_data )is missing

**Comment by tiagosiebler** [comment]
Hey, sorry for the late reply, looks like this endpoint hasn't been added yet. Will try and get it in with the next batch of changes.

**Comment by dutu** [comment]
No worries
