### ISSUE TITLE
kucoin-api-node

### ISSUE THREAD

**Issue by dutu** [tiagosiebler/binance#397]
Hi @tiagosiebler,
I was looking for a kucoin API module, but couldn't find any I like. I wanted to write my own and name it kucoin-api-node, but I see you have registered this name on npm and it seams to be abandoned.

I wanted to ask if I could take over this nom module name from you if you are not using it anymore.

Thank you!

**Comment by tiagosiebler** [comment]
Hi, apologies for blocking out the name - I will actually have a working kucoin module soon. No exact ETA yet, but hoping for sometime this quarter. I'll tag you if there's anything ready to test!

**Comment by dutu** [comment]
That's ok, I need one in the next few days. I'll choose another name

**Comment by dutu** [comment]
Thanks anyway
