### ISSUE TITLE
Incorrect Type Definition for WsMessage24hrTickerFormatted

### ISSUE THREAD

**Issue by h1b9b** [tiagosiebler/binance#398]
Hello,

I've noticed an issue with the TypeScript type definition for `WsMessage24hrTickerFormatted`. 
The `bestAsk` field always appears as `undefined`.  

According to the mapping for `24hrTickerEvent`, it seems that the correct field to use should be `bestAskPrice`.
However, this would introduce inconsistency in naming between `bestBid` and `bestAsk`.

**Comment by tiagosiebler** [comment]
Hmm I see the conflict. `bestBid` and `bestAskPrice`. Renaming it would be a breaking change for anyone that happens to be using it (which an accurate type definition might mitigate a bit, but not everyone uses typescript). Short term fix is improving the type to match what the data actually looks like, I'll get that added shortly. Consistency would be nice long term though...

**Comment by h1b9b** [comment]
Thanks for fixing the conflict so quickly!
Improving the type definitions to match the data structure sounds like the best short-term fix. 👍
