### ISSUE TITLE
browser ping issue

### ISSUE THREAD

**Issue by Tindtily** [tiagosiebler/binance#405]
https://github.com/tiagosiebler/binance/blob/2bb5172782e11af60ce0eb704301a524043542ca/src/websocket-client.ts#L300

for browser, i replaced 
```
ws.ping();
ws.pong();
```
 with the follow code 
```
            if(window){
                function getBuffer(bufferSuffix){
                    const ab = new ArrayBuffer(5);  
                    const view = new Uint8Array(ab);
                    view[0] = bufferSuffix; 
                    view[1] = 0x05;
                    view[2] = 0x00;  

                    view[3] = 0x00;
                    view[4] = 0x00;  
                    return ab
                }
                const pingBuffer = getBuffer(0x089);
                const pongBuffer = getBuffer(0x08a);

                // ping
               ws.send(pingBuffer);
               // pong
               ws.send(pongBuffer);
             } else {
               ws.ping();
               ws.pong();
             }
  ```
  
  the ping and pong works, but the socket connection break and reconnected every 10000ms(options.pingInterval)

**Comment by Tindtily** [comment]
Is this a normal phenomenon?

**Comment by Tindtily** [comment]
<img width="788" alt="image" src="https://github.com/tiagosiebler/binance/assets/5201107/ad70356a-1c84-4f45-9a7b-6c61e4d552a9">

**Comment by tiagosiebler** [comment]
Oh interesting, you've successfully managed to send raw ping/pong frames? I hadn't considered just sending them as hex for some reason. How come you've closed this? Did you get it working?

**Comment by Tindtily** [comment]
> Oh interesting, you've successfully managed to send raw ping/pong frames? I hadn't considered just sending them as hex for some reason. How come you've closed this? Did you get it working?

The chrome process ping and pong natively，and no need to process them manually.  So you can consider that the related code in your project can be removed when used in browser runtime.  

Since I no longer need to do this manually, I closed the issue
