### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by md-galib-hossain** [tiagosiebler/binance#407]
at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  } 
. I am trying to use binance api with my pc which is connected to my wifi. I have created a nodejs project with latest version. I have used kucoin api that working fine but binance is not working

**Comment by tiagosiebler** [comment]
This is a network issue. Is it happening every time you try to do anything, or only sometimes? Could it be you're making a request from an IP in a restricted region (e.g. the US)? Binance has active filtering by IP. I would suggest to try some simpler API calls to see if they return more info.

**Comment by md-galib-hossain** [comment]
most of the time gets the error and sometimes get the result. I live in
bangladesh & i think bangladesh is not restricted from binance.i have tried
on testnet and there it worked well only gives error on mainnet

**Comment by tiagosiebler** [comment]
ECONNRESET is a network error - if it happens frequently then your network has some kind of issue. 

You could try different internet connections to see if that improves things. Otherwise, it might be easier for you to test your project on a more stable environment like a VPS.
