### ISSUE TITLE
Request: REST Endpoints for SOR Trades

### ISSUE THREAD

**Issue by ozum** [tiagosiebler/binance#411]
Hi,

I can't find the below REST endpoints for trading. I would appreciate it if you could add them.

`POST /api/v3/sor/order/test`
`POST /api/v3/sor/order`

[Related Docs](https://binance-docs.github.io/apidocs/spot/en/#new-order-using-sor-trade)

Many thanks,

**Comment by tiagosiebler** [comment]
Released via #412, will be on npm shortly with v2.10.2. Thanks!
