### ISSUE TITLE
Portfolio Margin support 

### ISSUE THREAD

**Issue by davidpccu** [tiagosiebler/binance#428]
May I ask if there are plans to support Portfolio Margin?

**Comment by tiagosiebler** [comment]
Yes, will work to support it in the near future. 

Link for reference (for me): https://binance-docs.github.io/apidocs/pm/en/#general-info

**Comment by tiagosiebler** [comment]
Keeping this open as part of the planning process, thanks

**Comment by tiagosiebler** [comment]
Hey @davidpccu - have you upgraded your account to portfolio margin? If so, can you message me in telegram? I need some help testing API calls. This is my telegram: https://t.me/AlgoTraderL

**Comment by davidpccu** [comment]
I have not yet upgraded my account to Portfolio Margin. Currently, I mainly trade through Bybit Portfolio Margin

**Comment by tiagosiebler** [comment]
> I have not yet upgraded my account to Portfolio Margin. Currently, I mainly trade through Bybit Portfolio Margin

I have no means of testing the PM mode, so if you could (or anyone reading this) could provide read-only API keys to a sub account with portfolio margin enabled - we can continue testing a new REST client for it. 

You don't even need any funds in that account once its activated, if that's the concern. I just need a way of testing API calls are being accepted as expected, I don't need to test order fills. Anyone that wants to help out, feel free to drop me a message on telegram.

**Comment by tiagosiebler** [comment]
I'm not able to test it as portfolio margin is not available to me, if anyone needs this please get in touch. I'll need some read-only API keys to continue testing this. Feel free to DM me in telegram if preferred.

**Comment by davidpccu** [comment]
It seems that Binance has already removed the minimum wallet balance

https://www.binance.com/en/support/announcement/binance-removes-the-minimum-wallet-balance-requirement-for-portfolio-margin-2024-10-23-82e3f6645b554322bd3ffd75f57309b7

**Comment by tiagosiebler** [comment]
Interesting, it was preventing me for other reasons but looks like it's working now. Will look at resuming work on the PM client soon. Thanks for pointing that out.
