### ISSUE TITLE
Supporting missing endpoints/functionalities

### ISSUE THREAD

**Issue by JJ-Cro** [tiagosiebler/binance#430]
I would like to not here what is currently missing in the SDK and would be cool to have it eventually. For some of these, I will create a PR myself soon unless you can do it earlier :) 

**Completely new:** 

1) PORTFOLIO MARGIN category 
https://binance-docs.github.io/apidocs/pm

2) WEBSOCKET API 
https://binance-docs.github.io/apidocs/websocket_api/en/#change-log

    USDM WSAPI:
    https://binance-docs.github.io/apidocs/futures/en/#websocket-api

3) EUROPEAN OPTIONS  category 
- not sure how requested and how widely used, but missing as of now 

**Existing clients:**

##########SPOT###############
MAIN CLIENT - Wallet Endpoints
GET /sapi/v1/system/status
GET /sapi/v1/capital/config/getall
GET /sapi/v1/accountSnapshot
POST /sapi/v1/account/disableFastWithdrawSwitch
POST /sapi/v1/account/enableFastWithdrawSwitch
POST /sapi/v1/capital/withdraw/apply
GET /sapi/v1/capital/deposit/hisrec
GET /sapi/v1/capital/withdraw/history
GET /sapi/v1/capital/deposit/address
GET /sapi/v1/account/status
GET /sapi/v1/account/apiTradingStatus
GET /sapi/v1/asset/dribblet
POST /sapi/v1/asset/dust-btc
POST /sapi/v1/asset/dust
GET /sapi/v1/asset/assetDividend
GET /sapi/v1/asset/assetDetail
GET /sapi/v1/asset/tradeFee
POST /sapi/v1/asset/transfer
GET /sapi/v1/asset/transfer
POST /sapi/v1/asset/get-funding-asset  [X]
POST /sapi/v3/asset/getUserAsset [X]
POST /sapi/v1/asset/convert-transfer [X]
GET /sapi/v1/asset/convert-transfer/queryByPage [X]
GET /sapi/v1/asset/ledger-transfer/cloud-mining/queryByPage [X]
GET /sapi/v1/account/apiRestrictions
GET /sapi/v1/capital/contract/convertible-coins [X]
POST /sapi/v1/capital/contract/convertible-coins [X]
POST /sapi/v1/capital/deposit/credit-apply [X]
GET /sapi/v1/capital/deposit/address/list [X]
GET /sapi/v1/asset/wallet/balance [X]
GET /sapi/v1/asset/custody/transfer-history [X]
GET /sapi/v1/spot/delist-schedule [X]
GET /sapi/v1/capital/withdraw/address/list [X]
GET /sapi/v1/account/info [X]

MAIN CLIENT - Sub-Account Endpoints
POST /sapi/v1/sub-account/virtualSubAccount
GET /sapi/v1/sub-account/list
GET /sapi/v1/sub-account/sub/transfer/history
GET /sapi/v1/sub-account/futures/internalTransfer
POST /sapi/v1/sub-account/futures/internalTransfer
GET /sapi/v3/sub-account/assets
GET /sapi/v1/sub-account/spotSummary
GET /sapi/v1/capital/deposit/subAddress
GET /sapi/v1/capital/deposit/subHisrec
GET /sapi/v1/sub-account/status
POST /sapi/v1/sub-account/margin/enable
GET /sapi/v1/sub-account/margin/account
GET /sapi/v1/sub-account/margin/accountSummary
POST /sapi/v1/sub-account/futures/enable
GET /sapi/v1/sub-account/futures/account
GET /sapi/v1/sub-account/futures/accountSummary
GET /sapi/v1/sub-account/futures/positionRisk
POST /sapi/v1/sub-account/futures/transfer
POST /sapi/v1/sub-account/margin/transfer
POST /sapi/v1/sub-account/transfer/subToSub
POST /sapi/v1/sub-account/transfer/subToMaster
GET /sapi/v1/sub-account/transfer/subUserHistory
POST /sapi/v1/sub-account/universalTransfer
GET /sapi/v1/sub-account/universalTransfer
GET /sapi/v2/sub-account/futures/account
GET /sapi/v2/sub-account/futures/accountSummary
GET /sapi/v2/sub-account/futures/positionRisk
POST /sapi/v1/sub-account/blvt/enable
GET /sapi/v1/sub-account/subAccountApi/ipRestriction
DELETE /sapi/v1/sub-account/subAccountApi/ipRestriction/ipList
POST /sapi/v2/sub-account/subAccountApi/ipRestriction [X]
POST /sapi/v1/managed-subaccount/deposit
GET /sapi/v1/managed-subaccount/asset
POST /sapi/v1/managed-subaccount/withdraw
GET /sapi/v1/managed-subaccount/accountSnapshot [X]
GET /sapi/v1/managed-subaccount/queryTransLogForInvestor [X]
GET /sapi/v1/managed-subaccount/queryTransLogForTradeParent [X]
GET /sapi/v1/managed-subaccount/fetch-future-asset [X]
GET /sapi/v1/managed-subaccount/marginAsset [X]
GET /sapi/v4/sub-account/assets [X]
GET /sapi/v1/managed-subaccount/info [X]
GET /sapi/v1/sub-account/transaction-statistics [X]
GET /sapi/v1/managed-subaccount/deposit/address [X]
POST /sapi/v1/sub-account/eoptions/enable [X]
GET /sapi/v1/managed-subaccount/query-trans-log [X]

MAIN CLIENT - Market Data Endpoints
GET /api/v3/ping
GET /api/v3/time [X]
GET /api/v3/exchangeInfo
GET /api/v3/depth
GET /api/v3/trades
GET /api/v3/historicalTrades
GET /api/v3/aggTrades
GET /api/v3/klines
GET /api/v3/uiKlines [X]
GET /api/v3/avgPrice
GET /api/v3/ticker/24hr
GET /api/v3/ticker/tradingDay [X]
GET /api/v3/ticker/price
GET /api/v3/ticker/bookTicker
GET /api/v3/ticker

Websocket Market Streams

MAIN CLIENT - Spot Trading Endpoints
POST /api/v3/order/test
POST /api/v3/order
DELETE /api/v3/order
DELETE /api/v3/openOrders
GET /api/v3/order
POST /api/v3/order/cancelReplace
GET /api/v3/openOrders
GET /api/v3/allOrders
POST /api/v3/order/oco
POST /api/v3/orderList/oco
POST /api/v3/orderList/oto [X]
POST /api/v3/orderList/otoco [X]
DELETE /api/v3/orderList
GET /api/v3/orderList
GET /api/v3/allOrderList
GET /api/v3/openOrderList
POST /api/v3/sor/order
POST /api/v3/sor/order/test

MAIN CLIENT - Spot Account Endpoints
GET /api/v3/account
GET /api/v3/myTrades
GET /api/v3/rateLimit/order [X]
GET /api/v3/myPreventedMatches [X]
GET /api/v3/myAllocations [X]
GET /api/v3/account/commission [X]

MAIN-CLIENT - Margin Account/Trade
POST /sapi/v1/margin/borrow-repay
GET /sapi/v1/margin/borrow-repay
GET /sapi/v1/margin/allAssets
GET /sapi/v1/margin/allPairs
GET /sapi/v1/margin/priceIndex
POST /sapi/v1/margin/order
DELETE /sapi/v1/margin/order
DELETE /sapi/v1/margin/openOrders
POST /sapi/v1/margin/max-leverage [X]
GET /sapi/v1/margin/transfer [X]
GET /sapi/v1/margin/interestHistory [X]
GET /sapi/v1/margin/forceLiquidationRec [X]
GET /sapi/v1/margin/account
GET /sapi/v1/margin/order
GET /sapi/v1/margin/openOrders
GET /sapi/v1/margin/allOrders
POST /sapi/v1/margin/order/oco
DELETE /sapi/v1/margin/orderList
GET /sapi/v1/margin/orderList
GET /sapi/v1/margin/allOrderList [X]
GET /sapi/v1/margin/openOrderList [X]
GET /sapi/v1/margin/myTrades [X]
GET /sapi/v1/margin/maxBorrowable
GET /sapi/v1/margin/maxTransferable
GET /sapi/v1/margin/isolated/account
DELETE /sapi/v1/margin/isolated/account (HMAC SHA256) [x]
POST /sapi/v1/margin/isolated/account [X]
GET /sapi/v1/margin/isolated/accountLimit [X]
GET /sapi/v1/margin/isolated/allPairs [X]
POST /sapi/v1/bnbBurn [X]
GET /sapi/v1/bnbBurn [X]
GET /sapi/v1/margin/interestRateHistory [X]
GET /sapi/v1/margin/crossMarginData [X]
GET /sapi/v1/margin/isolatedMarginData [X]
GET /sapi/v1/margin/isolatedMarginTier [X]
GET /sapi/v1/margin/rateLimit/order [X]
GET /sapi/v1/margin/crossMarginCollateralRatio [X]
GET /sapi/v1/margin/exchange-small-liability [X]
POST /sapi/v1/margin/exchange-small-liability [X]
GET /sapi/v1/margin/exchange-small-liability-history [X]
GET /sapi/v1/margin/next-hourly-interest-rate [X]
GET /sapi/v1/margin/capital-flow [X]
GET /sapi/v1/margin/delist-schedule [X]
GET /sapi/v1/margin/available-inventory [X]
POST /sapi/v1/margin/manual-liquidation [X]
GET /sapi/v1/margin/leverageBracket [X]

MAIN CLIENT - User Data Streams
POST /api/v3/userDataStream
PUT /api/v3/userDataStream
DELETE /api/v3/userDataStream
POST /sapi/v1/userDataStream
PUT /sapi/v1/userDataStream
DELETE /sapi/v1/userDataStream
POST /sapi/v1/userDataStream/isolated
PUT /sapi/v1/userDataStream/isolated
DELETE /sapi/v1/userDataStream/isolated

MAIN CLIENT - Margin User Data Streams
POST /sapi/v1/margin/listen-key [X]
PUT /sapi/v1/margin/listen-key [X]
DELETE /sapi/v1/margin/listen-key [X]

MAIN CLIENT - Simple Earn Endpoints
GET /sapi/v1/simple-earn/flexible/list
GET /sapi/v1/simple-earn/locked/list
POST /sapi/v1/simple-earn/flexible/subscribe
POST /sapi/v1/simple-earn/locked/subscribe
POST /sapi/v1/simple-earn/flexible/redeem
POST /sapi/v1/simple-earn/locked/redeem
GET /sapi/v1/simple-earn/flexible/position
GET /sapi/v1/simple-earn/locked/position
GET /sapi/v1/simple-earn/account
GET /sapi/v1/simple-earn/flexible/history/subscriptionRecord [X]
GET /sapi/v1/simple-earn/locked/history/subscriptionRecord [X]
GET /sapi/v1/simple-earn/flexible/history/redemptionRecord [X]
GET /sapi/v1/simple-earn/locked/history/redemptionRecord [X]
GET /sapi/v1/simple-earn/flexible/history/rewardsRecord [X]
GET /sapi/v1/simple-earn/locked/history/rewardsRecord [X]
POST /sapi/v1/simple-earn/flexible/setAutoSubscribe [X]
POST /sapi/v1/simple-earn/locked/setAutoSubscribe [X]
GET /sapi/v1/simple-earn/flexible/personalLeftQuota [X]
GET /sapi/v1/simple-earn/locked/personalLeftQuota [X]
GET /sapi/v1/simple-earn/flexible/subscriptionPreview [X]
GET /sapi/v1/simple-earn/locked/subscriptionPreview [X]
GET /sapi/v1/simple-earn/flexible/history/rateHistory [X]
GET /sapi/v1/simple-earn/flexible/history/collateralRecord [X]

MAIN CLIENT - Dual Investment Endpoints
GET /sapi/v1/dci/product/list [X]
POST /sapi/v1/dci/product/subscribe [X]
GET /sapi/v1/dci/product/positions [X]
GET /sapi/v1/dci/product/accounts [X]
POST /sapi/v1/dci/product/auto_compound/edit-status [X]

MAIN CLIENT - Auto-Invest Endpoints
GET /sapi/v1/lending/auto-invest/target-asset/list [X]
GET /sapi/v1/lending/auto-invest/target-asset/roi/list [X]
GET /sapi/v1/lending/auto-invest/all/asset [X]
GET /sapi/v1/lending/auto-invest/source-asset/list [X]
POST /sapi/v1/lending/auto-invest/plan/add [X]
POST /sapi/v1/lending/auto-invest/plan/edit [X]
POST /sapi/v1/lending/auto-invest/plan/edit-status [X]
GET /sapi/v1/lending/auto-invest/plan/list [X]
GET /sapi/v1/lending/auto-invest/plan/id [X]
GET /sapi/v1/lending/auto-invest/history/list [X]
GET /sapi/v1/lending/auto-invest/index/info [X]
GET /sapi/v1/lending/auto-invest/index/user-summary [X]
POST /sapi/v1/lending/auto-invest/one-off [X]
GET /sapi/v1/lending/auto-invest/one-off/status [X]
POST /sapi/v1/lending/auto-invest/redeem [X]
GET /sapi/v1/lending/auto-invest/redeem/history [X]
GET /sapi/v1/lending/auto-invest/rebalance/history [X]

MAIN CLIENT - Staking Endpoints
POST /sapi/v1/eth-staking/eth/stake [X]
POST /sapi/v2/eth-staking/eth/stake [X]
POST /sapi/v1/eth-staking/eth/redeem [X]
GET /sapi/v1/eth-staking/eth/history/stakingHistory [X]
GET /sapi/v1/eth-staking/eth/history/redemptionHistory [X]
GET /sapi/v1/eth-staking/eth/history/rewardsHistory [X]
GET /sapi/v1/eth-staking/eth/quota [X]
GET /sapi/v1/eth-staking/eth/history/rateHistory [X]
GET /sapi/v1/eth-staking/account [X]
GET /sapi/v2/eth-staking/account [X]
POST /sapi/v1/eth-staking/wbeth/wrap [X]
GET /sapi/v1/eth-staking/wbeth/history/wrapHistory [X]
GET /sapi/v1/eth-staking/wbeth/history/unwrapHistory [X]
GET /sapi/v1/eth-staking/eth/history/wbethRewardsHistory [X]

MAIN CLIENT - Mining Endpoints
GET /sapi/v1/mining/pub/algoList [X]
GET /sapi/v1/mining/pub/coinList [X]
GET /sapi/v1/mining/worker/detail [X]
GET /sapi/v1/mining/worker/list [X]
GET /sapi/v1/mining/payment/list [X]
GET /sapi/v1/mining/payment/other [X]
GET /sapi/v1/mining/hash-transfer/config/details/list [X]
GET /sapi/v1/mining/hash-transfer/profit/details [X]
POST /sapi/v1/mining/hash-transfer/config [X]
POST /sapi/v1/mining/hash-transfer/config/cancel [X]
GET /sapi/v1/mining/statistics/user/status [X]
GET /sapi/v1/mining/statistics/user/list [X]
GET /sapi/v1/mining/payment/uid [X]

MAIN CLIENT - Futures
POST /sapi/v1/futures/transfer
GET /sapi/v1/futures/transfer
GET /sapi/v1/futures/histDataLink [X]

MAIN CLIENT - Futures Algo Endpoints
POST /sapi/v1/algo/futures/newOrderVp [X]
POST /sapi/v1/algo/futures/newOrderTwap [X]
DELETE /sapi/v1/algo/futures/order [X]
GET /sapi/v1/algo/futures/openOrders [X]
GET /sapi/v1/algo/futures/historicalOrders [X]
GET /sapi/v1/algo/futures/subOrders [X]

MAIN CLIENT - Spot Algo Endpoints
POST /sapi/v1/algo/spot/newOrderTwap [X]
DELETE /sapi/v1/algo/spot/order [X]
GET /sapi/v1/algo/spot/openOrders [X]
GET /sapi/v1/algo/spot/historicalOrders [X]
GET /sapi/v1/algo/spot/subOrders [X]

MAIN CLIENT - Portfolio Margin Pro Endpoints
GET /sapi/v1/portfolio/account [X]
GET /sapi/v1/portfolio/collateralRate [X]
GET /sapi/v1/portfolio/pmLoan [X]
POST /sapi/v1/portfolio/repay [X]
GET /sapi/v1/portfolio/interest-history [X]
GET /sapi/v1/portfolio/asset-index-price [X]
POST /sapi/v1/portfolio/auto-collection [X]
POST /sapi/v1/portfolio/asset-collection [X]
POST /sapi/v1/portfolio/bnb-transfer [X]
POST /sapi/v1/portfolio/repay-futures-switch [X]
POST /sapi/v1/portfolio/repay-futures-negative-balance [X]
GET /sapi/v1/portfolio/margin-asset-leverage [X]

MAIN CLIENT - BLVT Endpoints
GET /sapi/v1/blvt/tokenInfo [X]
POST /sapi/v1/blvt/subscribe [X]
GET /sapi/v1/blvt/subscribe/record [X]
POST /sapi/v1/blvt/redeem [X]
GET /sapi/v1/blvt/redeem/record [X]
GET /sapi/v1/blvt/userLimit [X]

MAIN CLIENT - Fiat Endpoints
GET /sapi/v1/fiat/orders [X]
GET /sapi/v1/fiat/payments [X]

MAIN CLIENT - C2C Endpoints
GET /sapi/v1/c2c/orderMatch/listUserOrderHistory [X]

MAIN CLIENT - VIP Loans Endpoints
GET /sapi/v1/loan/vip/ongoing/orders [X]
POST /sapi/v1/loan/vip/repay [X]
GET /sapi/v1/loan/vip/repay/history [X]
POST /sapi/v1/loan/vip/renew [X]
GET /sapi/v1/loan/vip/collateral/account [X]
POST /sapi/v1/loan/vip/borrow [X]
GET /sapi/v1/loan/vip/loanable/data [X]
GET /sapi/v1/loan/vip/collateral/data [X]
GET /sapi/v1/loan/vip/request/data [X]
GET /sapi/v1/loan/vip/request/interestRate [X]

MAIN CLIENT - Crypto Loans Endpoints
GET /sapi/v1/loan/income [X]
POST /sapi/v1/loan/borrow [X]
GET /sapi/v1/loan/borrow/history [X]
GET /sapi/v1/loan/ongoing/orders [X]
POST /sapi/v1/loan/repay [X]
GET /sapi/v1/loan/repay/history [X]
POST /sapi/v1/loan/adjust/ltv [X]
GET /sapi/v1/loan/ltv/adjustment/history [X]
GET /sapi/v1/loan/loanable/data [X]
GET /sapi/v1/loan/collateral/data [X]
GET /sapi/v1/loan/repay/collateral/rate [X]
POST /sapi/v1/loan/customize/margin_call [X]
POST /sapi/v1/loan/flexible/borrow(depreciated) [X]
POST /sapi/v2/loan/flexible/borrow [X]
GET /sapi/v1/loan/flexible/ongoing/orders(To be depreciated) [X]
GET /sapi/v2/loan/flexible/ongoing/orders [X]
GET /sapi/v1/loan/flexible/borrow/history(To be depreciated)
GET /sapi/v2/loan/flexible/borrow/history [X]
POST /sapi/v1/loan/flexible/repay(To be depreciated) [X]
POST /sapi/v2/loan/flexible/repay [X]
GET /sapi/v1/loan/flexible/repay/history(To be depreciated) [X]
GET /sapi/v2/loan/flexible/repay/history [X]
POST /sapi/v1/loan/flexible/adjust/ltv(To be depreciated) [X]
POST /sapi/v2/loan/flexible/adjust/ltv [X]
GET /sapi/v1/loan/flexible/ltv/adjustment/history(To be depreciated) [X]
GET /sapi/v2/loan/flexible/ltv/adjustment/history [X]
GET /sapi/v1/loan/flexible/loanable/data(depreciated) [X]
GET /sapi/v2/loan/flexible/loanable/data [X]
GET /sapi/v1/loan/flexible/collateral/data(depreciated) [X]
GET /sapi/v2/loan/flexible/collateral/data [X]

MAIN CLIENT - Copy Trading Endpoints
GET /sapi/v1/copyTrading/futures/userStatus [X]
GET /sapi/v1/copyTrading/futures/leadSymbol [X]

MAIN CLIENT - Pay Endpoints
GET /sapi/v1/pay/transactions [X]

MAIN CLIENT - Convert Endpoints
GET /sapi/v1/convert/exchangeInfo [X]
GET /sapi/v1/convert/assetInfo [X]
POST /sapi/v1/convert/getQuote
POST /sapi/v1/convert/acceptQuote
GET /sapi/v1/convert/orderStatus
POST /sapi/v1/convert/limit/placeOrder [X]
POST /sapi/v1/convert/limit/cancelOrder [X]
GET /sapi/v1/convert/limit/queryOpenOrders [X]
GET /sapi/v1/convert/tradeFlow

MAIN CLIENT - Rebate Endpoints
GET /sapi/v1/rebate/taxQuery [X]

MAIN CLIENT - NFT Endpoints
GET /sapi/v1/nft/history/transactions [X]
GET /sapi/v1/nft/history/deposit [X]
GET /sapi/v1/nft/history/withdraw [X]
GET /sapi/v1/nft/user/getAsset [X]

MAIN CLIENT - Binance Gift Card Endpoints
POST /sapi/v1/giftcard/createCode [X]
POST /sapi/v1/giftcard/buyCode [X]
POST /sapi/v1/giftcard/redeemCode [X]
GET /sapi/v1/giftcard/verify [X]
GET /sapi/v1/giftcard/cryptography/rsa-public-key [X]
GET /sapi/v1/giftcard/buyCode/token-limit [X]

##########USDM###############
USDM CLIENT - Market Data Endpoints
GET /fapi/v1/ping
GET /fapi/v1/time [X]
GET /fapi/v1/exchangeInfo
GET /fapi/v1/depth
GET /fapi/v1/trades
GET /fapi/v1/historicalTrades
GET /fapi/v1/aggTrades
GET /fapi/v1/klines
GET /fapi/v1/continuousKlines
GET /fapi/v1/indexPriceKlines
GET /fapi/v1/markPriceKlines
GET /fapi/v1/premiumIndexKlines [X]
GET /fapi/v1/premiumIndex
GET /fapi/v1/fundingRate
GET /fapi/v1/fundingInfo [X]
GET /fapi/v1/ticker/24hr
GET /fapi/v1/ticker/price
GET /fapi/v2/ticker/price [X]
GET /fapi/v1/ticker/bookTicker
GET /fapi/v1/openInterest
GET /futures/data/delivery-price [X]
GET /futures/data/openInterestHist
GET /futures/data/topLongShortAccountRatio
GET /futures/data/topLongShortPositionRatio
GET /futures/data/globalLongShortAccountRatio
GET /futures/data/takerlongshortRatio
GET /futures/data/basis [X]
GET /fapi/v1/lvtKlines
GET /fapi/v1/indexInfo
GET /fapi/v1/assetIndex [X]
GET /fapi/v1/constituents [X]

USDM CLIENT - Account/Trades Endpoints
POST /fapi/v1/positionSide/dual
GET /fapi/v1/positionSide/dual
POST /fapi/v1/multiAssetsMargin
GET /fapi/v1/multiAssetsMargin
POST /fapi/v1/feeBurn (HMAC SHA256) [X]
GET /fapi/v1/feeBurn (HMAC SHA256) [X]
POST /fapi/v1/order 
POST /fapi/v1/order/test [X]
PUT /fapi/v1/order
POST /fapi/v1/batchOrders
PUT /fapi/v1/batchOrders [X]
GET /fapi/v1/orderAmendment [X]
GET /fapi/v1/order
DELETE /fapi/v1/order
DELETE /fapi/v1/allOpenOrders
DELETE /fapi/v1/batchOrders
POST /fapi/v1/countdownCancelAll
GET /fapi/v1/openOrder
GET /fapi/v1/openOrders
GET /fapi/v1/allOrders
GET /fapi/v2/balance
GET /fapi/v2/account
POST /fapi/v1/leverage
POST /fapi/v1/marginType
POST /fapi/v1/positionMargin
GET /fapi/v1/positionMargin/history
GET /fapi/v2/positionRisk
GET /fapi/v1/userTrades
GET /fapi/v1/income
GET /fapi/v1/leverageBracket
GET /fapi/v1/adlQuantile
GET /fapi/v1/forceOrders
GET /fapi/v1/apiTradingStatus
GET /fapi/v1/commissionRate
GET /fapi/v1/income/asyn [X]
GET /fapi/v1/income/asyn/id [X]
GET /fapi/v1/order/asyn [X]
GET /fapi/v1/order/asyn/id [X]
GET /fapi/v1/trade/asyn [X]
GET /fapi/v1/trade/asyn/id [X]

USDM CLIENT - User Data Streams
POST /fapi/v1/listenKey
PUT /fapi/v1/listenKey
DELETE /fapi/v1/listenKey

USDM CLIENT - Portfolio Margin Pro Endpoints
GET /fapi/v1/pmAccountInfo [X]

##########COINM###############
COINM CLIENT - Market Data Endpoints
GET /dapi/v1/ping
GET /dapi/v1/time [X]
GET /dapi/v1/exchangeInfo
GET /dapi/v1/depth
GET /dapi/v1/trades
GET /dapi/v1/historicalTrades
GET /dapi/v1/aggTrades
GET /dapi/v1/premiumIndex
GET /dapi/v1/fundingRate
GET /dapi/v1/fundingInfo [X]
GET /dapi/v1/klines
GET /dapi/v1/continuousKlines
GET /dapi/v1/indexPriceKlines
GET /dapi/v1/markPriceKlines
GET /dapi/v1/premiumIndexKlines [X]
GET /dapi/v1/ticker/24hr
GET /dapi/v1/ticker/price
GET /dapi/v1/ticker/bookTicker
GET /dapi/v1/constituents [X]
GET /dapi/v1/openInterest
GET /futures/data/delivery-price [X]
GET /futures/data/openInterestHist
GET /futures/data/topLongShortAccountRatio
GET /futures/data/topLongShortPositionRatio
GET /futures/data/globalLongShortAccountRatio
GET /futures/data/takerBuySellVol
GET /futures/data/basis

COINM CLIENT - Websocket Market Streams

COINM CLIENT - Account/Trades Endpoints
POST /dapi/v1/positionSide/dual (HMAC SHA256)
GET /dapi/v1/positionSide/dual (HMAC SHA256)
POST /dapi/v1/order
PUT /dapi/v1/order (HMAC SHA256)
POST /dapi/v1/batchOrders (HMAC SHA256)
PUT /dapi/v1/batchOrders (HMAC SHA256)
GET /dapi/v1/orderAmendment (HMAC SHA256)
GET /dapi/v1/order (HMAC SHA256)
DELETE /dapi/v1/order (HMAC SHA256)
DELETE /dapi/v1/allOpenOrders (HMAC SHA256)
DELETE /dapi/v1/batchOrders (HMAC SHA256)
POST /dapi/v1/countdownCancelAll (HMAC SHA256)
GET /dapi/v1/openOrder (HMAC SHA256)
GET /dapi/v1/openOrders (HMAC SHA256)
GET /dapi/v1/allOrders (HMAC SHA256)
GET /dapi/v1/balance (HMAC SHA256)
GET /dapi/v1/account (HMAC SHA256)
POST /dapi/v1/leverage (HMAC SHA256)
POST /dapi/v1/marginType (HMAC SHA256)
POST /dapi/v1/positionMargin (HMAC SHA256)
GET /dapi/v1/positionMargin/history (HMAC SHA256)
GET /dapi/v1/positionRisk (HMAC SHA256)
GET /dapi/v1/userTrades (HMAC SHA256)
GET /dapi/v1/income (HMAC SHA256)
GET /dapi/v1/leverageBracket [X]
GET /dapi/v2/leverageBracket
GET /dapi/v1/forceOrders
GET /dapi/v1/adlQuantile
GET /dapi/v1/commissionRate (HMAC SHA256)
GET /dapi/v1/income/asyn (HMAC SHA256) [X]
GET /dapi/v1/income/asyn/id (HMAC SHA256) [X]

COINM CLIENT - User Data Streams
POST /dapi/v1/listenKey
PUT /dapi/v1/listenKey
DELETE /dapi/v1/listenKey

COINM CLIENT - Classic Portfolio Margin Endpoints
GET /dapi/v1/pmExchangeInfo [X]
GET /dapi/v1/pmAccountInfo [X]

**Comment by JJ-Cro** [comment]
This has been done! :)

**Comment by Arvin-J** [comment]
/fapi/v1/premiumIndex   is missing
