### ISSUE TITLE
Issue: WebSocket Client Not Using Proxy Agent in binance Library

### ISSUE THREAD

**Issue by prite36** [tiagosiebler/binance#472]
When using the WebsocketClient in the binance npm library with a proxy agent configured via HttpsProxyAgent, the WebSocket client does not seem to route through the specified proxy. Instead, it appears to use my public IP address directly, bypassing the proxy, which results in an error message from Binance:

> WebSocket error: Invalid API-key, IP, or permissions for action, request ip: [public IP address]

The WebSocket connection does not seem to recognize the HttpsProxyAgent settings in wsOptions and instead connects directly using my public IP, which does not match the whitelisted IP on Binance, causing the connection to be rejected.

### Code Example
Here’s the code I used, following the documentation for proxy configuration:
```
import { WebsocketClient } from 'binance';
import { HttpsProxyAgent } from 'https-proxy-agent';

const binanceWs = new WebsocketClient({
    api_key: 'binance-api-key',
    api_secret: 'binance-api-secret',
    beautify: true,
    wsOptions: { 
        agent: new HttpsProxyAgent('http://<proxy_host>:<proxy_port>') 
    }
});
```

### System Information
 - Node.js version: 20.17.0
 -  binance library version: 2.13.11
 - https-proxy-agent version: 7.0.5

**Comment by tiagosiebler** [comment]
Is this with the user data stream? The user data stream requires a listen key, which is created by making a REST API call. I'm wondering if the REST API call isn't using the proxy. Can you try this (pseudo code, please double check it): 
```typescript
import { WebsocketClient } from 'binance';
import { HttpsProxyAgent } from 'https-proxy-agent';

const binanceWs = new WebsocketClient({
    api_key: 'binance-api-key',
    api_secret: 'binance-api-secret',
    beautify: true,
    wsOptions: { 
        agent: new HttpsProxyAgent('http://<proxy_host>:<proxy_port>') 
    },
   requestOptions{
       agent: new HttpsProxyAgent('http://<proxy_host>:<proxy_port>')
   }
});
```

This is to ensure that the proxy config is also passed to the REST client:
https://github.com/tiagosiebler/binance/blob/master/src/websocket-client.ts#L756

**Comment by prite36** [comment]
@tiagosiebler  Thank you so much for the guidance! Adding the requestOptions with the httpsAgent for the REST API call did the trick. Here's the code that worked for me:

```const binanceWs = new WebsocketClient({
    api_key: 'binance-api-key',
    api_secret: 'binance-api-secret',
    beautify: true,
    wsOptions: { 
        agent: new HttpsProxyAgent('http://<proxy_host>:<proxy_port>') 
    },
    requestOptions: {
        httpsAgent: new HttpsProxyAgent('http://<proxy_host>:<proxy_port>')
    }
});
```

I appreciate the help! The WebSocket client is now correctly routing through the proxy, and everything is working as expected.

**Comment by tiagosiebler** [comment]
Perfect! Glad to hear it. Will think about how to make this easier, this feels a bit too hidden.
