### ISSUE TITLE
SimpleEarn Redeem Flexible product params

### ISSUE THREAD

**Issue by marosvida** [tiagosiebler/binance#474]
Hello, currently method for Redeeming flexible product in SimpleEarn (url: POST /sapi/v1/simple-earn/flexible/redeem) only supports params as:
   {
        positionId: string;
    },
    
but the API itself supports also other parameters such as flag redeemAll, or for me most important field amount (to be redeemed). Also the naming is not positionId but productId as stated in binance docs.

Can you please adjust params object type, so this fields can be set?

Thank You!

**Comment by JJ-Cro** [comment]
Thanks for noticing! Can you submit a PR for that? If not, I can change tommorow!

**Comment by marosvida** [comment]
I opened PR: https://github.com/tiagosiebler/binance/pull/480 , please check
