### ISSUE TITLE
NumberType throws an error

### ISSUE THREAD

**Issue by emiliocr90** [tiagosiebler/binance#482]
![image](https://github.com/user-attachments/assets/9ce122bb-469f-401b-a956-8e91e8aab823)

Why does it say 'NewFuturesOrderParams\<string\>'?

interface declaration at futures.d.ts:
![image](https://github.com/user-attachments/assets/2743b1a8-c1df-4ef7-8c54-9205895256c1)

**Comment by JJ-Cro** [comment]
I think you will need to provide some more details. Can you send code snippet so we can see which fuction that is.

**Comment by emiliocr90** [comment]
> I think you will need to provide some more details. Can you send code snippet so we can see which fuction that is.
Hi mate.
Thanks for the quick reply. Here you are:
![image](https://github.com/user-attachments/assets/c82d1531-81d9-4370-9b8a-b20d1220fc32)

**Comment by emiliocr90** [comment]
qtiesToClose variable declaration:
![image](https://github.com/user-attachments/assets/9f2a8546-cd92-46d2-a912-5dda9b699dbc)

**Comment by JJ-Cro** [comment]
Lets wait for @tiagosiebler , I checked but I dont see any type interference. 

Just make sure you provide whats needed for the function just like in the docs.

**Comment by tiagosiebler** [comment]
Looks like a mistake. There's some flexibility for these "string in number" fields, but only for some endpoints. The type is supposed to default to number but allow type injection (not needed in most cases). In this case, for the submit multiple orders endpoint, it's accidentally hardcoded as a "string" for these number fields, while the docs clearly show decimal. I'll correct this shortly after checking a few things here.

**Comment by tiagosiebler** [comment]
Merged a fix via #485, should be on npm shortly. Thanks for reporting this - let me know if you notice any other issues.
