### ISSUE TITLE
How to see  fills , and fee in spot orders submited by  submitNewOrder()  when resolved to PARTIALLY_FILLED ?

### ISSUE THREAD

**Issue by Kos-M** [tiagosiebler/binance#486]
Hello there , 

My use case is the following : 
A user submits the order , but due market conditions , the ```submitNewOrder()``` resolves in PARTIALLY_FILLED  status.

So the user needs to recheck in a loop with ```getOrder()``` but there is no fills prop there...

Is there any way to "see" order details such as fills , qty  filled  , fees , by order id  and after spot order submission ?

Thank you in advance :100:

**Comment by JJ-Cro** [comment]
I would really suggest to use websocket for order updates. You will avoid problems like these! 

It gives you realtime update.

**Comment by Kos-M** [comment]
Seems this is the way to go on that use case.
Ill leave this issue open for few days , maybe someone else will suggest something different , just in case.

In any way thanks for the suggestion @JJ-Cro , much appreciated it.

**Comment by tiagosiebler** [comment]
I'd definitely recommend @JJ-Cro 's suggested approach as well. Always better to use websockets to let updates flow to you, so you don't have to use up request weight limits with regular polls.

Subscribing to this stream is easy enough with my SDK, here's an example:
https://github.com/tiagosiebler/binance/blob/master/examples/ws-userdata.ts#L77-L79

`wsClient.subscribeUsdFuturesUserDataStream()` is what initiates the subscription request (for the usd futures market), and the WS client will keep your session active (incl managing any listen key renewals). Other markets are there too.

Alternatively, if you reaally don't want to take the async websocket approach, the order submission endpoint does have an extra parameter that defines when/how the REST API call responds to your order submission - take a look at `newOrderRespType` in binance's API docs. The minimal one is a simple ACK (doesn't even wait for a fill to happen - gives you a reply asap). If there's a way to wait for partial fills to complete, it would be with that property. Even then, I'd still recommend the async/websocket approach.

**Comment by Kos-M** [comment]
Thanks for your input @tiagosiebler  too.
Indeed seems a bit more resource intense , the polling way on that case.
I need to make some refactors to use  websockets for that too.

Im testing the  websocketClient.subscribeSpotTrades( pair ) 
Seems at random times reports trade events with ignored = true , do you know why ? Or what it means?

**Comment by tiagosiebler** [comment]
Hey @Kos-M - no idea on that one, would be curious too. The docs give no information either:
https://developers.binance.com/docs/binance-spot-api-docs/web-socket-streams#trade-streams

**Comment by Kos-M** [comment]
Indeed  , maybe fills are not supported at all in  this context at all.

My workarround on this  is to listen for [UserData Strewam](https://developers.binance.com/docs/binance-spot-api-docs/user-data-stream) 

and manually calculating  the fills with `executionReport` events.
As this is progression to the "FILLED" state..

**Comment by tiagosiebler** [comment]
That is the way to go in my opinion. You can use the REST response as a confirmation your order has been received, but if you need a guaranteed confirmation of fill (even for market orders), you're safer & faster using the user data stream's execution event (even if you simply wait for the "filled" state and ignore the partial fills along the way).
