### ISSUE TITLE
SimpleEarn flexible rewards history - new option in field type

### ISSUE THREAD

**Issue by marosvida** [tiagosiebler/binance#494]
Hello,

There was added new option in type field in parameters for requesting SimpleEarn flexible rewards history.

Documentation: https://developers.binance.com/docs/simple_earn/history/Get-Flexible-Rewards-History

I added option, and tested it.

Please review PR:  https://github.com/tiagosiebler/binance/pull/493

Thanks!

**Comment by tiagosiebler** [comment]
Merged! Thanks!
