### ISSUE TITLE
#withdraw returns {"code":-1022,"msg":"Signature for this request is not valid."} when I use characters within the name that need to be escaped

### ISSUE THREAD

**Issue by rapides** [tiagosiebler/binance#59]
Hi, I'm trying to withdraw some funds but they always answer me with the code 1022. Used version `1.3.3`

What have I investigated yet?
1. Checked if my API keys are correct (I did #newOrder which is SIGNED as well and it worked)
2. Checked if mandatory permissions have been enabled for those keys (had to tick withdrawal option on the permissions list and restrict my IP address)
3. Changed `recvWindow` to many different values between 5000-60000 with no results
4. Changed `handleDrift` to true with no result
5. Changed the `_getTime()` function to `return new Date().getTime() + 10000;` with no results (based on @zoeyg suggestion located in https://github.com/zoeyg/binance/issues/34)

My current configuration:

![image](https://user-images.githubusercontent.com/2733755/40403747-21094bde-5e54-11e8-9ca8-f255ff1c8b7a.png)

My withdrawal function:

![image](https://user-images.githubusercontent.com/2733755/40403801-7175a978-5e54-11e8-80d3-7f6d7065e12f.png)

Please advise

### Update
Finally, I figured out what happened there. By adding a 'name' param like '[${STAGE}]: Main KS's wallet in ETH' it seems that your library does something wrong with building URL params because of the escape codes.

I suggest to fix it as it may cause unexpected and difficult to detect bugs.

Thanks!

**Comment by rxcod9** [comment]
FIXED

https://github.com/zoeyg/binance/pull/75

**Comment by tiagosiebler** [comment]
Fixed in #122
