### ISSUE TITLE
Track/provide IP used weight limit from response header

### ISSUE THREAD

**Issue by jboxxx** [tiagosiebler/binance#76]
Is there a way to see the current request weight usage from this library?  The [binance api documentation](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#ip-limits) states: 

"Every request will contain X-MBX-USED-WEIGHT-(intervalNum)(intervalLetter) in the response headers which has the current used weight for the IP for all request rate limiters defined."

Is there a way to target this header so we don't lock ourselves out after multiple requests to the rest API?

**Comment by zoeyg** [comment]
An easy, short term solution for 1.x would probably be to just append the response object as an argument to the callback.

Perhaps long term, should we have a more robust solution that would automatically backoff?

**Comment by tiagosiebler** [comment]
Fixed in #122. You can call `restClient.getRateLimitStates()` on any of the REST clients. It's tracked and updated automatically as you make requests (by parsing response headers from any request you make).
