### ISSUE TITLE
onUserData example not properly working.

### ISSUE THREAD

**Issue by thisisloze** [tiagosiebler/binance#98]
I have tried the onUserData example in the manual.
This is the message I get after I have connected to the ws.
Here is my code:
`        const binanceWS = new api.BinanceWS(true);
        const ret = binanceWS
        .onUserData(
            this.binance,
            data => {
                //console.log(data);
            },
            60000
        ) // Optional, how often the keep alive should be sent in milliseconds
        .then(ws => {
            console.log(ws)
        });`

Here is what happens.

`WebSocket {
  _events:
   [Object: null prototype] { message: [Function], error: [Function] },
  _eventsCount: 2,
  _maxListeners: undefined,
  readyState: 0,
  bytesReceived: 0,
  extensions: {},
  protocol: '',
  _binaryType: 'nodebuffer',
  _finalize: [Function: bound finalize],
  _closeFrameReceived: false,
  _closeFrameSent: false,
  _closeMessage: '',
  _closeTimer: null,
  _finalized: false,
  _closeCode: 1006,
  _receiver: null,
  _sender: null,
  _socket: null,
  _ultron: null,
  protocolVersion: 13,
  _isServer: false,
  url:
   'wss://stream.binance.com:9443/ws/6ios2GAP9wkLT8IjkxMuzQNSpgH7kBuCf1a1oxxIQ5fVFIoQcySeYmfnEf5D',
  _req:
   ClientRequest {
     _events:
      [Object: null prototype] {
        socket: [Function],
        error: [Function],
        response: [Function],
        upgrade: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,`
     
     I have left it open while I made some trades to see if there was any messages sent. There was not.

**Comment by theNodeMan** [comment]
Same here

**Comment by tiagosiebler** [comment]
Fixed in #122 - check the example here:
https://github.com/tiagosiebler/binance/blob/v2.0.0/beta/examples/ws-userdata.ts
