### ISSUE TITLE
Cannot post OCO Orders

### ISSUE THREAD

**Issue by lejacobroy** [tiagosiebler/binance#99]
Hi,

Thanks for the wonderful library!
I think it need to be updated to support OCO orders, as it's a different endpoint not declared in the rest.js file.

As per [the docs](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#new-oco-trade), OCO orders need to be posted to the `/api/v3/order/oco` endpoint.

Is is planned to add this endpoint, or is there a workaround for the time being?

Thank you!

**Comment by CavalrysHere** [comment]
Yeah, i also need it. OCO feature is missing somehow.

**Comment by tiagosiebler** [comment]
If you make a PR to add the missing API method, I'll happily review it.

**Comment by tiagosiebler** [comment]
Fixed in #122
